language: python
python:
    - "2.7"
before_install:
    - pip install pytest pytest-cov
    - pip install netcdf4-python
    - pip install python-dateutil
    - pip install pytz
script:
    - py.test